### ISSUE TITLE
Training in other language

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-translator/sign-language-translator#36]
This looks a great engine. Is this possible to train this pipeline to other language or the engine could be used for other language? and what are the license terms and conditions for this repo? Please guide and help.

**Comment by mdsrqbl** [comment]
Yes, the engine is designed to be highly customizable. You just have to inherit the `slt.languages.TextLanguage` & `slt.languages.SignLanguage` classes to build the rule-based translator. Then that can be used to synthesize data for a deep learning model.

The format your dataset needs to be in and the code examples are all over the [docs](https://slt.readthedocs.io/), readme and this [notebook](https://github.com/sign-language-translator/notebooks/blob/main/translation/concatenative_synthesis.ipynb) but are incomplete. I would encourage you to go through them and let me know what is confusing, incomplete, old or just isn't helpful so I can improve the documentation according to the user needs.

Apologies for the late response. Been through a lot of turmoil recently :/

Best Wishes
